Fixes #49 navbar issue
BugBustersCommunity/website pull request #60
Opened 2022-10-01 13:00 UTC by PritamSarbajna

# Fixes #49

## What is the change?
I have changed the hovering issue in navbar.

## Related issue?
closes: #49 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Contribution Guidelines]() while contributing.
-   [x] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-   [ ] I have made corresponding changes to the documentation.
-   [x] I have tested the code before submission.
-   [x] I have formatted the code . (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:

**_Before_**

https://user-images.githubusercontent.com/90236635/193410685-bc74f170-8d7a-46ca-864a-e69654818920.mp4

**_After_**

https://user-images.githubusercontent.com/90236635/193410652-2a4dd7cd-53d8-4b96-8437-0a68d27d95ce.mp4

2022-10-01 16:52 UTC, siddhi-244 requested changes
It would be great if you can improve the navbar in mobile view too !

2022-10-04 10:23 UTC, siddhi-244 commented
Please resolve merge conflicts

2022-10-09 06:00 UTC, PritamSarbajna commented
@siddhi-244 to make the navbar mobile compatible it needs another issue !

2022-10-09 06:19 UTC, Aditi-Singh16 approved these changes

2022-10-09 06:21 UTC, siddhi-244 approved these changes

2022-10-09 06:21 UTC, merged