Created README.md for Bug Busters Website repo
BugBustersCommunity/website pull request #7
Opened 2022-07-16 05:27 UTC by muditchoudhary

# What I have done
- Created a README.md for Bug Busters Website repo

# What I have added
- About Bug Busters community section
- How to contribute section
- How to run the project section
-  About Project Admin

# Additional Information
- There is one link **here are tutorials using GUI tools.** is not pointing to a tutorial but pointing to Embellish self repo. Is this a mistake? Can I add this https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/overview/getting-started-with-github-desktop Getting started with GitHub Desktop docs link?

2022-07-16 08:48 UTC, siddhi-244 commented
> Closes #1
> 
> # What I have done
> * Created a README.md for Bug Busters Website repo
> 
> # What I have added
> * About Bug Busters community section
> * How to contribute section
> * How to run the project section
> * About Project Admin
> 
> # Additional Information
> * There is one link **here are tutorials using GUI tools.** is not pointing to a tutorial but pointing to Embellish self repo. Is this a mistake? Can I add this https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/overview/getting-started-with-github-desktop Getting started with GitHub Desktop docs link?

That would be a mistake. You can change that

2022-07-16 08:49 UTC, siddhi-244 requested changes
One more thing. Just add the technology stack in one line!

2022-07-16 09:10 UTC, Aditi-Singh16 commented on README.md
> +
Add @Aditi-Singh16  as project maintainer too!

2022-07-17 04:57 UTC, muditchoudhary commented
Hey!! admins made the requested changes.

2022-07-17 05:07 UTC, siddhi-244 approved these changes
LGTM 🥳

2022-07-17 06:02 UTC, Aditi-Singh16 commented
@muditchoudhary nice work!
merging :D

2022-07-17 06:02 UTC, Aditi-Singh16 approved these changes

2022-07-17 06:02 UTC, merged

2022-07-17 06:22 UTC, muditchoudhary commented
> @muditchoudhary nice work! merging :D

Yayy!!! :) Thank you :blush: